[arguments.py]
  bug: crbug.com/626703
  [test_element_reference[frame\]]
    expected: FAIL

  [test_element_reference[window\]]
    expected: FAIL

  [test_no_such_element_from_other_frame[closed\]]
    expected: FAIL

  [test_no_such_element_from_other_frame[open\]]
    expected: FAIL

  [test_no_such_element_from_other_window_handle[closed\]]
    expected: FAIL

  [test_no_such_element_from_other_window_handle[open\]]
    expected: FAIL

  [test_no_such_shadow_root_from_other_frame[closed\]]
    expected: FAIL

  [test_no_such_shadow_root_from_other_frame[open\]]
    expected: FAIL

  [test_no_such_shadow_root_from_other_window_handle[closed\]]
    expected: FAIL

  [test_no_such_shadow_root_from_other_window_handle[open\]]
    expected: FAIL

  [test_no_such_shadow_root_with_unknown_shadow_root]
    expected: FAIL
